storage = "/tmp/test"
shared_group = "users"

[ca]
cn = "Teapot Root CA"
duration = 21900 # 21900 days = ~ 60 years

[certificates]
duration = 5 # 60 days = ~ two monts

[[hosts]]
domain = "test.com"
user = "luca"
