storage = "/tmp"
shared_group = "users"

[ca]
cn = "Your Self-Signed CA"
duration = 21900 # 21900 days = ~ 60 years

[certificates]
duration = 90 # 90 days = ~ three monts

[[ hosts ]]
domain = "example.com"
user = "user1"

[[ hosts ]]
domain = "acme.com"
user = "user2"
